search-path = [
    ".",
    "odoo",
    "odoo_addons",
    "C:/Users/msi/AppData/Local/Python/pythoncore-3.14-64/Lib/site-packages"
]

site-package-path = [
    "C:/Users/msi/AppData/Local/Python/pythoncore-3.14-64/Lib/site-packages"
]

errors = { missing-import = "ignore", unbound-name = "ignore", missing-attribute = "ignore", bad-assignment = "ignore", bad-index = "ignore", unsupported-operation = "ignore", bad-argument-type = "ignore", missing-module-attribute = "ignore" }
