search-path = [
    ".",
    "backend",
    "odoo_addons",
    "backend/.venv/Lib/site-packages",
    "C:/Users/msi/AppData/Local/Python/pythoncore-3.14-64/Lib/site-packages"
]

site-package-path = [
    "backend/.venv/Lib/site-packages",
    "C:/Users/msi/AppData/Local/Python/pythoncore-3.14-64/Lib/site-packages"
]

errors = { missing-import = "ignore", unbound-name = "ignore", unused-import = "ignore" }
